name: Flutter CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      KEY_JKS: ${{ secrets.KEY_JKS }}
      KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
      KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}

    steps:
    
    - uses: actions/checkout@v1
    
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    
    - uses: subosito/flutter-action@v1
      with:
        channel: 'stable' # or 'dev' or 'beta'
    
    - run: echo ${{ secrets.KEY_JKS }} | base64 -d > android/app/upload.jks
    
    # Check for any formatting issues in the code.
    - run: flutter format --set-exit-if-changed .
    
    # Statically analyze the Dart code for any errors.
    - run: flutter analyze .
    
    - run: flutter pub get
    - run: flutter build apk --release --split-per-abi
    
    - name: Attach arm64-v8a file
      uses: actions/upload-artifact@v2
      with:
        name: Quizzler_arm64-v8a
        path: build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
    
    - name: Attach armeabi-v7a file
      uses: actions/upload-artifact@v2
      with:
        name: Quizzler_armeabi-v7a
        path: build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk
          
    - name: Attach x86_64 file
      uses: actions/upload-artifact@v2
      with:
        name: Quizzler_x86_64
        path: build/app/outputs/flutter-apk/app-x86_64-release.apk
